### ISSUE TITLE
[Unidentified Tracker]: static.cloudflareinsights.com

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/trackerdb#74] opened 2023-08-17 09:05 UTC
### Request

static.cloudflareinsights.com

### Location

https://www.vivint.com/

### Tracker Company/Organization

Cloudflare

### Company/Organization Website

https://www.cloudflare.com/en-gb/web-analytics/

### Company/Organization Privacy Policy

https://www.cloudflare.com/en-gb/privacypolicy/

### Category

None

**Comment by philipp-classen** [comment] 2023-08-17 10:27
Duplicate of https://github.com/ghostery/trackerdb/issues/55

(I copied the information over)

**Closed by philipp-classen** 2023-08-17 10:27 UTC
Labels: enhancement
