### ISSUE TITLE
https://www.youtube.com/ 

### ISSUE THREAD

**Issue by Auntie100** [ghostery/trackerdb#199] opened 2024-01-08 03:28 UTC
### Request

https://www.youtube.com/watch?v=rKcqIj03oFE

### Location

https://www.youtube.com/

### Tracker Company

YouTube

### Company Website

https://www.youtube.com/

### Privacy Policy

https://www.youtube.com/

### Describe the company

Ghostery stopped providing a Firefox alternative page to view YouTube videos without ads. What happened? Now I have to slog through Github?

### Category

Advertising

### Request Type

other

### Additional Information

 I simply click on a desired YouTube video and am directed to the ad blocker page:  https://www.youtube.com/watch?v=rKcqIj03oFE

### Filters

```shell
NO IDEA
```

**Comment by philipp-classen** [comment] 2024-01-08 12:04
Sorry, I have to close it, since it is out of scope of the TrackerDB project.

Maybe it is an issue on the Ghostery extension (not blocking ads on YouTube)? Here is a ticket were we collect notes on open problems for YouTube: https://github.com/ghostery/broken-page-reports/issues/267 If you noticed a problem, feel free to leave a comment here. YouTube is a complex page, but being aware of issues helps us to reproduce and improve.

**Closed by philipp-classen** 2024-01-08 12:04 UTC
Labels: enhancement
