### ISSUE TITLE
Error: serialized engine version mismatch, expected 650 but got 644

### ISSUE THREAD

**Issue by rosell-dk** [ghostery/trackerdb#280] opened 2024-04-30 13:58 UTC
Reproduce:

npm install --save @ghostery/trackerdb
npm list
└── @cliqz/adblocker@1.27.2
└── @ghostery/trackerdb@1.0.125

Run this script (taken from the README)
import { readFileSync } from 'node:fs';
import loadTrackerDB from '@ghostery/trackerdb';

const engine = readFileSync('./node_modules/@ghostery/trackerdb/dist/trackerdb.engine');
const trackerDB = await loadTrackerDB(engine);

Error:
C:\tracktest\node_modules\@cliqz\adblocker\dist\cjs\src\engine\engine.js:134
            throw new Error(`serialized engine version mismatch, expected ${exports.ENGINE_VERSION} but got ${serializedEngineVersion}`);
                  ^

Error: serialized engine version mismatch, expected 650 but got 644
    at FilterEngine.deserialize (C:\tracktest\node_modules\@cliqz\adblocker\dist\cjs\src\engine\engine.js:134:19)
    at loadTrackerDBEngine (file:///C:/tracktest/node_modules/@ghostery/trackerdb/dist/mjs/index.js:4:34)
    at file:///C:/tracktest/test/test.mjs:8:25
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2

**Comment by philipp-classen** [comment] 2024-05-07 13:59
This was caused by an outdated version of the adblocker library. Now fixed in https://github.com/ghostery/trackerdb/pull/292. 

Thanks for reporting!

**Closed by philipp-classen** 2024-05-07 13:59 UTC
Labels: bug
